import "./globals.css";

// Import the required components
import { getServerSession } from "next-auth";
import  SessionProvider  from "@/utils/SessionProvider";
import Navbar from "../components/Navbar";
import reactoast from "@/components/reactoast";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
   <html lang="en">
    <body className="{inter.className}">
    <SessionProvider session={session}>
      <Navbar />
      {children}
      <reactoast />
    </SessionProvider>
    </body>
    </html>
  ); 
}